# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/react-browser-hooks
    docker:
      - image: circleci/node:10.16-browsers
    environment:
      BROWSERSTACK_PARALLEL_RUNS: '5'
      BROWSERSTACK_USE_AUTOMATE: '1'
      BROWSERSTACK_PROJECT_NAME: 'react-browser-hooks'
    steps:
      - run:
          name: setup dynamic environment variables
          command: |
              echo 'export BROWSERSTACK_BUILD_ID="$CIRCLE_BRANCH"' >> $BASH_ENV
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run test:coverage
      - run: |
          npm install coveralls
          cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run: npm run test:acceptance
